## This is a Rough Notebook that I prepared while learning basic Numpy functions.

## Author: Chirag Parmar

In [1]:
python_list = [1,2,3,4,5]

In [2]:
python_list

[1, 2, 3, 4, 5]

In [3]:
import numpy as np

In [4]:
numpy_array = np.array(python_list)

In [5]:
numpy_array

array([1, 2, 3, 4, 5])

In [6]:
listx = list(range(100))
listy = list(range(100))

In [7]:
arr_x = np.array(listx)
arr_y = np.array(listy)

In [8]:
arr_x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [9]:
a = listx + listy

In [10]:
def list_sum():
    z = []
    for i in range(len(listx)):
        z.append(listx[i] + listy[i])
    return z    

In [11]:
list_sum()

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198]

In [12]:
def numpy_sum():
    arr_z = arr_x + arr_y

In [13]:
from timeit import Timer

## Time Functions

In [14]:
timer_obj1 = Timer("list_sum()", setup="from __main__ import list_sum")
timer_obj2 = Timer("numpy_sum()", setup="from __main__ import numpy_sum")

In [15]:
print("Pure Python Version", timer_obj1.timeit(number=1000))
print("Numpy Version", timer_obj2.timeit(number=1000))

Pure Python Version 0.049077200000000154
Numpy Version 0.0032927000000002593


In [16]:
"-".join(str(n) for n in range(100))

'0-1-2-3-4-5-6-7-8-9-10-11-12-13-14-15-16-17-18-19-20-21-22-23-24-25-26-27-28-29-30-31-32-33-34-35-36-37-38-39-40-41-42-43-44-45-46-47-48-49-50-51-52-53-54-55-56-57-58-59-60-61-62-63-64-65-66-67-68-69-70-71-72-73-74-75-76-77-78-79-80-81-82-83-84-85-86-87-88-89-90-91-92-93-94-95-96-97-98-99'

In [17]:
list1 = []

In [18]:
np_array = np.array(list1)

In [19]:
"+".join(str(n) for n in range(100))

'0+1+2+3+4+5+6+7+8+9+10+11+12+13+14+15+16+17+18+19+20+21+22+23+24+25+26+27+28+29+30+31+32+33+34+35+36+37+38+39+40+41+42+43+44+45+46+47+48+49+50+51+52+53+54+55+56+57+58+59+60+61+62+63+64+65+66+67+68+69+70+71+72+73+74+75+76+77+78+79+80+81+82+83+84+85+86+87+88+89+90+91+92+93+94+95+96+97+98+99'

In [20]:
import timeit

In [21]:
timeit.timeit('"+".join(str(n) for n in range(100))')

48.3769415

## Creating a NP Array

In [22]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,11,11]])

In [23]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 11, 11]])

In [24]:
arr.size

12

In [25]:
arr.dtype

dtype('int32')

In [26]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 11, 11]])

In [27]:
arr.shape

(4, 3)

In [28]:
arr.ndim

2

In [29]:
type(arr)

numpy.ndarray

In [30]:
arr.dtype

dtype('int32')

In [31]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.arange(1,12,2)

array([ 1,  3,  5,  7,  9, 11])

In [33]:
np.zeros(3)

array([0., 0., 0.])

In [34]:
np.ones(4)

array([1., 1., 1., 1.])

In [35]:
np.linspace(start=5, stop=10, num=5)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [36]:
np.linspace(start=5, stop=10)

array([ 5.        ,  5.10204082,  5.20408163,  5.30612245,  5.40816327,
        5.51020408,  5.6122449 ,  5.71428571,  5.81632653,  5.91836735,
        6.02040816,  6.12244898,  6.2244898 ,  6.32653061,  6.42857143,
        6.53061224,  6.63265306,  6.73469388,  6.83673469,  6.93877551,
        7.04081633,  7.14285714,  7.24489796,  7.34693878,  7.44897959,
        7.55102041,  7.65306122,  7.75510204,  7.85714286,  7.95918367,
        8.06122449,  8.16326531,  8.26530612,  8.36734694,  8.46938776,
        8.57142857,  8.67346939,  8.7755102 ,  8.87755102,  8.97959184,
        9.08163265,  9.18367347,  9.28571429,  9.3877551 ,  9.48979592,
        9.59183673,  9.69387755,  9.79591837,  9.89795918, 10.        ])

In [37]:
np.array([2, 5, 8, 6, 4, 12, 16, 15]).ndim

1

In [38]:
np.linspace(start=17, stop=31, num=50)

array([17.        , 17.28571429, 17.57142857, 17.85714286, 18.14285714,
       18.42857143, 18.71428571, 19.        , 19.28571429, 19.57142857,
       19.85714286, 20.14285714, 20.42857143, 20.71428571, 21.        ,
       21.28571429, 21.57142857, 21.85714286, 22.14285714, 22.42857143,
       22.71428571, 23.        , 23.28571429, 23.57142857, 23.85714286,
       24.14285714, 24.42857143, 24.71428571, 25.        , 25.28571429,
       25.57142857, 25.85714286, 26.14285714, 26.42857143, 26.71428571,
       27.        , 27.28571429, 27.57142857, 27.85714286, 28.14285714,
       28.42857143, 28.71428571, 29.        , 29.28571429, 29.57142857,
       29.85714286, 30.14285714, 30.42857143, 30.71428571, 31.        ])

In [39]:
np.append(arr, [1,2,3])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 11, 11,  1,  2,  3])

In [40]:
np.delete(arr, 4)

array([ 1,  2,  3,  4,  6,  7,  8,  9, 11, 11, 11])

In [41]:
python_list = [5,4,3,2,1]

In [42]:
np.delete(python_list, 3)

array([5, 4, 3, 1])

In [43]:
np.sort(python_list)

array([1, 2, 3, 4, 5])

In [44]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 11, 11]])

In [45]:
arr.sort()

In [46]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 11, 11]])

In [47]:
python_list = [5,4,3,2,1]

In [48]:
python_list.sort()

In [49]:
print(python_list)

[1, 2, 3, 4, 5]


In [50]:
arr_3 = np.arange(30)

In [51]:
np.reshape(arr_3, (6,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [52]:
L = [10, 2, 7, 8, 3, 22, 54, 12, 13, 46, 23, 25, 41]

In [53]:
L_1  = np.array(L)

In [54]:
type(L_1)

numpy.ndarray

In [55]:
L_1.sort()

In [56]:
L_1

array([ 2,  3,  7,  8, 10, 12, 13, 22, 23, 25, 41, 46, 54])

In [57]:
np.delete(L_1, 4)

array([ 2,  3,  7,  8, 12, 13, 22, 23, 25, 41, 46, 54])

In [58]:
L.append(53)

In [59]:
L

[10, 2, 7, 8, 3, 22, 54, 12, 13, 46, 23, 25, 41, 53]

In [60]:
np.reshape(L, (2,7))

array([[10,  2,  7,  8,  3, 22, 54],
       [12, 13, 46, 23, 25, 41, 53]])

In [61]:
L[-1]

53

In [62]:
arr_3 = np.reshape(np.arange(25), (5,5))

In [63]:
arr_3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [64]:
arr_3[:2,3:]

array([[3, 4],
       [8, 9]])

In [65]:
arr_3[1:5:2, 0:5:2]

array([[ 5,  7,  9],
       [15, 17, 19]])

In [66]:
np.zeros(shape=(2,2,2,2), order='C')

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])

In [67]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 11, 11]])

In [68]:
np.resize(arr,(5,5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 11],
       [11, 11,  1,  2,  3],
       [ 4,  5,  6,  7,  8],
       [ 9, 11, 11, 11,  1]])

In [69]:
rng = np.random.RandomState(10)

In [70]:
rng.normal(loc=5, scale=2, size=100)

array([7.66317301, 6.43055795, 1.90919942, 4.9832323 , 6.24267195,
       3.55982888, 5.53102317, 5.21709705, 5.00858286, 4.65079958,
       5.86605238, 7.40607475, 3.06986866, 7.05654816, 5.45726026,
       5.89027523, 2.72679558, 5.27027376, 7.969074  , 2.84039023,
       1.04454344, 1.51325541, 5.53214033, 9.76993466, 7.24738251,
       8.34524443, 5.19829843, 7.79599275, 4.45750402, 6.22640837,
       4.46536562, 3.90138197, 5.26541659, 4.04771597, 7.61694616,
       5.39002656, 5.80041998, 4.32473533, 7.51294453, 3.536061  ,
       6.3204631 , 4.29825622, 3.12113328, 4.02132557, 3.39081772,
       4.57460472, 4.32171951, 5.62433987, 6.13030534, 4.70515948,
       4.94818933, 5.57818841, 3.92024186, 6.41632004, 6.68444948,
       5.40716159, 9.78940733, 6.83491788, 4.77545506, 4.27563911,
       4.53563549, 3.9965422 , 7.25757031, 3.60437994, 4.83775563,
       3.94140784, 7.09236571, 2.16288794, 4.27500163, 4.75618862,
       5.63871284, 5.9218058 , 4.56842022, 6.97814491, 5.62950

In [71]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 11, 11]])

In [72]:
from random import seed

In [73]:
seed(2)

In [74]:
arr_5 = np.array([1,2,3,4,5,6,7,8,9,10])

In [75]:
arr_5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
rng.normal(loc=5, scale=2, size=10)

array([5.23495132, 1.18508622, 3.15418147, 5.93950287, 4.71126647,
       4.1997233 , 4.40803229, 6.69641722, 6.41366091, 3.42546215])

In [77]:
np.hstack((arr_5, rng.normal(loc=5, scale=2, size=10)))

array([ 1.        ,  2.        ,  3.        ,  4.        ,  5.        ,
        6.        ,  7.        ,  8.        ,  9.        , 10.        ,
        5.58588145,  4.0583855 ,  9.80865121,  3.52128652,  4.37434249,
        4.30223616,  4.12194753,  5.28220834,  5.54609864,  1.7628585 ])

In [78]:
np.vstack((arr_5, rng.normal(loc=5, scale=2, size=10)))

array([[ 1.        ,  2.        ,  3.        ,  4.        ,  5.        ,
         6.        ,  7.        ,  8.        ,  9.        , 10.        ],
       [ 3.85377328,  2.35910491,  7.47241065,  9.93065016,  7.76646446,
         5.69246623,  7.04503221,  5.33362053,  8.31343325,  6.33577922]])